let ERROR_CODES = {
  NODE_HAS_CHILDREN: 1,
  FORBIDDEN_ATTRIBUTE: 2,
  UNACCOUNTED_L10NNAME: 3,
  ILLEGAL_ELEMENT: 4,
  NAMED_ELEMENTS_DIFFER_IN_TYPE: 5,
  LOCALIZABLE_ATTRIBUTE_IN_SOURCE: 6,
  ILLEGAL_ATTRIBUTE_IN_L10N: 7,
};

exports.ERROR_CODES = ERROR_CODES;
